[project]
name = "rechtspraak-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chatlas>=0.14.0",
    "openai>=2.7.1",
    "pandas>=2.3.3",
    "pydantic>=2.12.4",
    "transformers>=4.57.1",
]
